### PR TITLE
Upgrade ActiveSupport [sh26648]

### PR DESCRIPTION
**Pull request by ExMember**
https://app.shortcut.com/transparentclassroom/story/26648/upgrade-rails-in-i18n-migrations

### CODE REVIEW

**Review by zspencer — APPROVED** [review]
Thank you!

**Review by zspencer — APPROVED** [review]
Why does the Gem have a Gemfile.lock? I thought that was considered 'bad-idea-jeans'

**Comment by ExMember** [comment]
It was. Guidance on that has changed. As I understand it, a Gemfile.lock for a gem allows developers to all use the version so there is consistency there, but it's not the same as dictating versions for project that use the gems.

**Comment by zspencer** [comment]
Ah got it. Probably due to the rise of Appraisal and similar multi-gemfile compatibility checking solutions.

**Pull request merged**
